// <auto-generated />
namespace ClaseUno.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterProducto_add_descripcion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterProducto_add_descripcion));
        
        string IMigrationMetadata.Id
        {
            get { return "202003141832364_AlterProducto_add_descripcion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
